// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeaponAccountingProject.Data;

#nullable disable

namespace WeaponAccountingProject.Migrations
{
    [DbContext(typeof(WeaponAccountingContext))]
    [Migration("20241112103100_AddOfficer")]
    partial class AddOfficer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Completeness", b =>
                {
                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int>("CompletenessItemId")
                        .HasColumnType("int");

                    b.HasKey("WeaponId", "CompletenessItemId")
                        .HasName("PK__Complete__FA3AD65F738CC68B");

                    b.HasIndex("CompletenessItemId");

                    b.ToTable("Completeness", (string)null);
                });

            modelBuilder.Entity("CompletenessItemWeapon", b =>
                {
                    b.Property<int>("CompletenessItemId")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("CompletenessItemId", "WeaponId");

                    b.ToTable("CompletenessItemWeapon");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.CompletenessItem", b =>
                {
                    b.Property<int>("CompletenessItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompletenessItemId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CompletenessItemId")
                        .HasName("PK__Complete__E27DCAEB0A4440DB");

                    b.ToTable("CompletenessItem");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OfficerSoldierId")
                        .HasColumnType("int");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA497D37E3B7E");

                    b.HasIndex("OfficerSoldierId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Soldier", b =>
                {
                    b.Property<int>("SoldierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoldierId"));

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OfficerSoldierId")
                        .HasColumnType("int");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SoldierId")
                        .HasName("PK__Soldier__7596D901DF73424B");

                    b.HasIndex("LocationId");

                    b.HasIndex("OfficerSoldierId");

                    b.ToTable("Soldier");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponId"));

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecordNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SoldierId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.HasKey("WeaponId")
                        .HasName("PK__Weapon__541D0AF125D9407D");

                    b.HasIndex("LocationId");

                    b.HasIndex("SoldierId");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Officer", b =>
                {
                    b.HasBaseType("WeaponAccountingProject.Models.Soldier");

                    b.ToTable("Officer");
                });

            modelBuilder.Entity("Completeness", b =>
                {
                    b.HasOne("WeaponAccountingProject.Models.CompletenessItem", null)
                        .WithMany()
                        .HasForeignKey("CompletenessItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Completen__Compl__4D94879B");

                    b.HasOne("WeaponAccountingProject.Models.Weapon", null)
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .IsRequired()
                        .HasConstraintName("FK__Completen__Weapo__4CA06362");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Location", b =>
                {
                    b.HasOne("WeaponAccountingProject.Models.Officer", null)
                        .WithMany("locationsOnDuty")
                        .HasForeignKey("OfficerSoldierId");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Soldier", b =>
                {
                    b.HasOne("WeaponAccountingProject.Models.Location", "Location")
                        .WithMany("Soldiers")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK__Soldier__Locatio__693CA210");

                    b.HasOne("WeaponAccountingProject.Models.Officer", null)
                        .WithMany("soldiersOnDuty")
                        .HasForeignKey("OfficerSoldierId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Weapon", b =>
                {
                    b.HasOne("WeaponAccountingProject.Models.Location", "Location")
                        .WithMany("Weapons")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK__Weapon__Location__6B24EA82");

                    b.HasOne("WeaponAccountingProject.Models.Soldier", "Soldier")
                        .WithMany("Weapons")
                        .HasForeignKey("SoldierId")
                        .HasConstraintName("FK__Weapon__SoldierI__6A30C649");

                    b.Navigation("Location");

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Officer", b =>
                {
                    b.HasOne("WeaponAccountingProject.Models.Soldier", null)
                        .WithOne()
                        .HasForeignKey("WeaponAccountingProject.Models.Officer", "SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Location", b =>
                {
                    b.Navigation("Soldiers");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Soldier", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("WeaponAccountingProject.Models.Officer", b =>
                {
                    b.Navigation("locationsOnDuty");

                    b.Navigation("soldiersOnDuty");
                });
#pragma warning restore 612, 618
        }
    }
}
